name: ai-exercise-tracker
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.26.0
  - opencv>=4.10.0
  - pip
  - pip:
      - opencv-python>=4.10.0
      - mediapipe>=0.10.20
      - websockets>=11.0
      - websocket-client>=1.8.0
      - python-dotenv>=1.1.0
      - aiortc>=1.6.0
