name: vero-perception
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.26.0
  - opencv>=4.10.0
  - pillow>=10.4.0
  - pip
  - pip:
      - torch>=2.5.0
      - torchvision>=0.20.0
      - ultralytics>=8.3.0
      - mediapipe>=0.10.20
      - opencv-python>=4.10.0
      - scipy>=1.14.0
      - requests>=2.32.0
      - websocket-client>=1.8.0
      - python-dotenv>=1.1.0
      - face-recognition>=1.3.0
      - dlib>=19.24.0
      - aiortc>=1.6.0
      - asyncio>=3.4.3
      - websockets>=11.0
