version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ai_exercise_tracker
      POSTGRES_PASSWORD: ai_exercise_tracker
      POSTGRES_DB: ai_exercise_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai_exercise_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
