version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: vero
      POSTGRES_PASSWORD: vero_wellness_2024
      POSTGRES_DB: vero_wellness
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vero"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: